#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: "{ AR }"

# Short bio or description (displayed in the header)
description: Angela Riggs | Quality Advocate. Quality = Compassion + Curiosity

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars0.githubusercontent.com/u/10238548?s=400&u=3ee43493bd3e42e0a8e80ffab64d24d2f19c97fc&v=4

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: 
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: 
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: angelariggs_

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://angelariggs.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

# Conversion
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

# kramdown:
#   auto_ids:       true
#   entity_output:  as_char
#   toc_levels:     1..6
#   smart_quotes:   lsquo,rsquo,ldquo,rdquo
#   input:          GFM
#   hard_wrap:      false
#   footnote_nr:    1

permalink: /:title/
paginate_path: /page:num

# The release of Jekyll Now that you're using
version: v3.4.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed
  sass_dir: _sass

# Use the following plug-ins
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem.

plugins_dir:
  - jekyll-feed

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
