# Site settings
title: Musings of a Junior Dev
email: riggs.ang@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "angelariggs.github.io/" # the base hostname & protocol for your site
twitter_username: AngelaRiggs_
github_username:  angelariggs
timezone: US/Pacific

# Build settings
markdown: kramdown

# Defaults
scope: 
  path: ""
  type: "posts"
values:
  layout: "default"
  author: "Angela Riggs"
  date: "YYYY-MM-DD"

scope:
  path: ""
  type: "drafts"
values: 
  layout: "default"
  author: "Angela Riggs"
  date: "YYYY-MM-DD"