# Site settings
title: Musings of a Junior Dev
email: riggs.ang@gmail.com
description: Site Description
baseurl: "" # the subpath of your site, e.g. /blog/
url: "angelariggs.github.io/" # the base hostname & protocol for your site
twitter_username: AngelaRiggs_
github_username:  angelariggs
timezone: US/Pacific

# Build settings
markdown: kramdown

# Defaults
scope: 
  path: ""
  type: "posts"
values:
  layout: "default"
  author: "Angela Riggs"
  date: "YYYY-MM-DD"

scope:
  path: ""
  type: "drafts"
values: 
  layout: "default"
  author: "Angela Riggs"
  date: "YYYY-MM-DD"